#配置数据源
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/study?serverTimezone=UTC
    username: root
    password: 123456
#修改数据源
#    type: com.alibaba.druid.pool.DruidDataSource
    #初始化会删除掉之前的表，一般不用
    #initialization-mode: always
    schema: classpath*:*.sql
#让swagger生效需要配置
swagger2:
  enable: true
  title: lq
  version: 1.0.0